"""add referred by

Revision ID: 2164418a57c4
Revises: db8d730f67b2
Create Date: 2026-01-04 01:48:43.413063

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2164418a57c4'
down_revision: Union[str, Sequence[str], None] = 'db8d730f67b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referred_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['referred_by'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'referred_by')
    # ### end Alembic commands ###
